### ISSUE TITLE
hyperterminator: Hyperterm theme for cybernetic organisms

### ISSUE THREAD

**Issue by brianzelip** [bnb/awesome-hyper#108]
[hyperterminator](https://www.npmjs.com/package/hyperterminator): Hyperterm theme for cybernetic organisms, by the hard working @jxnblk.

**Comment by iamstarkov** [comment]
@brianzelip so, would you submit a pull-request?

**Comment by darahak** [comment]
Closing this stale issue.
Open a PR if you want to add it.
