### ISSUE TITLE
Predawn for Hyperterm

### ISSUE THREAD

**Issue by jamiewilson** [bnb/awesome-hyper#111]
[predawn-hyperterm](https://github.com/jamiewilson/predawn-hyperterm) - Predawn is a dark interface and syntax theme for Sublime Text, Atom, iTerm, Terminal and now, HyperTerm.

**Comment by iamstarkov** [comment]
pls submit a pull-request

**Comment by darahak** [comment]
Closing this stale issue.
Open a PR if you want to add it.
