### ISSUE TITLE
Theme: hyperterm-zigorat

### ISSUE THREAD

**Issue by dotamir** [bnb/awesome-hyper#119]
![hyperterm-zigorat](https://github.com/dotamir/hyperterm-zigorat) - A minimal Syntax theme for hyperterm

**Comment by simonmeusel** [comment]
Is this your theme? You can add it by creating a [Pull Request](https://github.com/bnb/awesome-hyper/pulls) 😄

**Comment by iamstarkov** [comment]
@dotamir pls submit a pull-request

**Comment by darahak** [comment]
Already done with #136.
