### ISSUE TITLE
Typo in summary for hpm-cli

### ISSUE THREAD

**Issue by matchai** [bnb/awesome-hyper#120]
[The summary provided](https://github.com/bnb/awesome-hyper/blame/217e6c9bb9b36e448e70fb40bb77f023bc884826/README.md#L30) says:
> A plugin manager for HyperHyper

[The summary on npm](https://www.npmjs.com/package/hpm-cli) for hpm-cli says:
> A plugin manager for Hyper.app

**Comment by matheuss** [comment]
#121
