### ISSUE TITLE
Theme browser

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [bnb/awesome-hyper#131]
I've created a theme browser that may be of value: [https://hyperthemes.matthi.coffee](https://hyperthemes.matthi.coffee)

**Comment by srimajji** [comment]
sick! 💯

**Comment by bnb** [comment]
@MatthiasWinkelmann Awesome - do you want to submit a PR to add it to the Resources list?

**Comment by MatthiasWinkelmann** [comment]
submitted – always feels dirty to submit PRs with links to own work :)

**Comment by bnb** [comment]
Thanks @MatthiasWinkelmann 😉 Merged.
