### ISSUE TITLE
Support for non-monospace fonts?

### ISSUE THREAD

**Issue by mdfederici** [bnb/awesome-hyper#139]
I'm new to hyperterm - seems awesome so far but I'd really like to use a non-monospace font. When I do right now, it seems like the cursor is just totally in the wrong place even when there is no text. I might be doing something incorrectly though. If I use the default font of 

`Menlo, "DejaVu Sans Mono", "Lucida Console", monospace`

the cursor appears as I would expect. The same with other monospace fonts such as 

`"Courier New", Courier, monospace`

However If I use a font like

`Papyrus, fantasy`

the cursor then becomes too far to the right by like 10-15 characters while the font does render correctly. I can imagine that this will only reliably work with monotype fonts but I love me some papyrus. Any chance of supporting a proper cursor position with a non-monotype font?

**Comment by mdfederici** [comment]
In case it wasn't clear, i understand that there are other problems with non monotype besides the cursor but that one is the most obvious annoyance to me vs say "ls" not having things line up.

**Comment by matheuss** [comment]
@mdfederici this repository is just a list of plugins and themes for hyper – could you please open your issue on [zeit/hyper](https://github.com/zeit/hyper)? 😄
