### ISSUE TITLE
Package categories

### ISSUE THREAD

**Issue by darahak** [bnb/awesome-hyper#141]
It's not a big issue, since there are not a lot of packages right now, but what do you think about sorting it a little bit?
It would be easier to navigate and search.

Example with [Awesome Node.js](https://github.com/sindresorhus/awesome-nodejs).

**Comment by iamstarkov** [comment]
lets close it for now, and reopen when will do have a lot of packages

**Comment by bnb** [comment]
I've been thinking about this for themes for a while - what would your suggestions for categories be?

**Comment by caesar** [comment]
Would be nice to at least group related plugins together – for example, `hyper-statusline` should be next to `hyperline`, and `hyper-lastpass` should be next to `hyper-1password`. Lots of other examples. At the moment it's just random.

Same for the themes – for example, all the `solarized` ones should be together. I appreciate that finding characteristics by which to sort or group the themes is harder than with the plugins, though.

If this is too difficult, even alphabetical order would be better than random, though nowhere near as good as a logical order.
(I know they are listed in the order they were added, but that's effectively random.)

**Comment by bnb** [comment]
How about we try to draft some general categories? Things like Productivity (1pass), Fun (the John Ceena one), and a few others. Maybe try 4 to start out with?

**Comment by darahak** [comment]
I agree, it would be a good start to create a few categories, and sorting them alphabetically would be neat.
I'll come back with some ideas.

**Comment by darahak** [comment]
### Productivity
Pretty much anything that changes Hyper to **help** the user, with no configuration needed, or not much.

Examples:
- [hyperterm-1password](https://www.npmjs.com/package/hyperterm-1password)
- [hyperterm-lastpass](https://www.npmjs.com/package/hyperterm-lastpass)
- [hyperterm-tabs](https://www.npmjs.com/package/hyperterm-tabs)
- [hyperlinks](https://www.npmjs.com/package/hyperlinks)

### Customization
Includes packages that allows the user to change Hyper's appearance and functionalities.

Examples:
- [hyperterm-visor](https://github.com/CWSpear/hyperterm-visor)
- [hyper-stylesheet](https://www.npmjs.com/package/hyper-stylesheet)
- [hyperterm-overlay](https://www.npmjs.com/package/hyperterm-overlay)
- [hyperterm-transparent-bg](https://www.npmjs.com/package/hyperterm-transparent-bg)

### Fun
Packages that are not really useful, but adds a bit of entertainment in the terminal.

Examples:
- [hyper-john](https://www.npmjs.com/package/hyper-john)
- [htyt](https://www.npmjs.com/package/htyt)

And of course, we could sort all packages alphabetically.
Any suggestions?

**Comment by bnb** [comment]
@darahak Love it! Looks perfect. 👌

**Comment by darahak** [comment]
@bnb Should I wait for second opinions before making a PR?
Also, I'm afraid of the merge conflicts with other PRs if I apply an alphabetic sort on the lists.

**Comment by bnb** [comment]
@darahak Nope, feel free to submit a PR now! I think two steps is best - submit categories, and then  we can start alphabetically sorting once we've got categories to minimize the merge conflicts in the meantime 👍

**Comment by darahak** [comment]
FYI if I make the alphabetical sort, I will also need to update the contributing rules.

> Link additions should be added to the bottom of the relevant category.

For contributors who use Atom, it has a [package](https://atom.io/packages/markdown-sort-list) for sorting Markdown lists (could help if the edited list gets too long).

**Comment by bnb** [comment]
@darahak I was thinking about the sorting of them today. Ideally we'd like to not need people to jump out to a text editor to sort them correctly. I think the best way is to note it in the `CONTRIBUTING.md` file, in the PR template, and then manually check ourselves. when a PR is submitted.

One thing that would be nice is to automate it. At this point, I'm fairly frustrated with the build system we're using. I'd like to rework it, and would be interesting to see if we could integrate alphabetical order into the build process.

**Comment by darahak** [comment]
We could probably automate a check with [Travis CI](https://travis-ci.org/) for example and then, use something like [Danger](http://danger.systems/) to automatically ask for changes on PRs that don't follow the guidelines?
