### ISSUE TITLE
hyperterm-sync-settings -> hyper-sync-settings ?

### ISSUE THREAD

**Issue by sesam** [bnb/awesome-hyper#150]
npm says hyperterm-sync-settings is deprecated, replaced by hyper-sync-settings
Is npm a trustable source? Then I can make a patch+pull req if you want?

**Comment by dfrankland** [comment]
npm speaks the truth. https://github.com/dfrankland/hyper-sync-settings

**Comment by bnb** [comment]
@sesam That'd be awesome if you could patch + pull! ❤️

**Comment by gmaggess** [comment]
+1

**Comment by darahak** [comment]
Fixed by #192.
