### ISSUE TITLE
Paste last selected text

### ISSUE THREAD

**Issue by wmertens** [bnb/awesome-hyper#171]
The Mac Terminal.app has a shortcut <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> that pastes the last selected text, without needing to copy it to the clipboard.

It also works between terminal windows.

Would it be possible to implement this feature?

**Comment by iamstarkov** [comment]
Hi, @wmertens,

Thanks for your opinion, Hyper has this option in place, check out `copyOnSelect` option in  [configuration](https://hyper.is/#cfg)
![screen shot 2017-01-09 at 11 50 59](https://cloud.githubusercontent.com/assets/559321/21764218/3aef7a12-d662-11e6-9502-53c5ab51812f.png)

PS. Next time, you gotta create an issue in relevant repo, [hyper](https://github.com/zeit/hyper/) one. we can help you here, but in that repo you would get help in matter of hours =)

**Comment by wmertens** [comment]
OMG I must have been low on coffee :) lol, sorry, and thanks for the pointer! 💯

**Comment by iamstarkov** [comment]
no worries =)
