### ISSUE TITLE
 Chinese fonts overlap

### ISSUE THREAD

**Issue by JonasGao** [bnb/awesome-hyper#173]
![default](https://cloud.githubusercontent.com/assets/4549584/21582327/1af5b278-d08e-11e6-87a8-769217266dfa.PNG)

hyper version: 1.0.0
windows version: Windows 10 1607

**Comment by bnb** [comment]
Hi there @JonasGao. I believe you need to report this issue to the main Hyper repo, which can be found here: https://github.com/zeit/hyper

This repo isn't the main repo where issues for Hyper are tracked and resolved. 

Let me know if I can help at all with getting an issue in on the application's repo!

**Comment by JonasGao** [comment]
Oh~ thank you very much (=ﾟωﾟ)ﾉ
