### ISSUE TITLE
[vim][YCM][Chinese]cannot import name 'GetCurrentDirectory'

### ISSUE THREAD

**Issue by FrontMage** [bnb/awesome-hyper#189]
When using vim and YouCompleteMe in hyper, it posts above error.
Also Chinese words doesn't seem show right in hyper.
Any help here?

**Comment by iamstarkov** [comment]
what is YouCompleteMe?

**Comment by iamstarkov** [comment]
everything works fine in other editors?

**Comment by iamstarkov** [comment]
@FrontMage would you mind open an issue in relevant hyper repo?

**Comment by FrontMage** [comment]
It's a vim plugin for auto completion, yes everything works in ubuntu default terminal.

**Comment by iamstarkov** [comment]
@FrontMage thanks
