### ISSUE TITLE
Some packages don't work on Windows

### ISSUE THREAD

**Issue by jmreicha** [bnb/awesome-hyper#193]
It would be nice to get a warning for packages that don't work on Windows.

**Comment by darahak** [comment]
It looks like it would be difficult to keep it up-to-date :man_shrugging: 

IMO this is a package maintainer's responsibility.
If there is no Windows support, they should indicate it in their `README`.
If it's supposed to work on Windows, but it actually doesn't, file an issue?

But if you have ideas about how to make this viable, we're listening :wave:

**Comment by jmreicha** [comment]
Yeah, I don't know of a good way to make it viable 😭

**Comment by iamstarkov** [comment]
@jmreicha what packages didnt work for you on windows?

**Comment by dsbert** [comment]
These plugins do not currently support Windows.

- hyperline
- hypercwd
- hyperterm-paste
- hyper-statusline
