### ISSUE TITLE
Project Shell Scripts

### ISSUE THREAD

**Issue by corbanb** [bnb/awesome-hyper#209]
Does anyone know of a way to configure hyper to open a certain layout and run a few commands in each window on open? Like I need 2x2 panes to cd into different dirs and run a few command in each when working on local node.js project.

Thoughts?

**Comment by iamstarkov** [comment]
I think you need https://www.npmjs.com/package/hyperlayout. have your read through readme?

**Comment by corbanb** [comment]
I had. just not came across this one. I think this is a great start to the issue I was coming into. Thanks @iamstarkov.

**Comment by iamstarkov** [comment]
@corbanb, glad to help
