### ISSUE TITLE
Theme: hypermaterial-vibrancy

### ISSUE THREAD

**Issue by danielheyman** [bnb/awesome-hyper#211]
Hi, I have been quite interested in the material vibrancy theme that was on here in the past but it had a lot of issues with compatibility and vibrancy wasn't working. I've updated it and published it here if you're interested in adding it to the list: https://www.npmjs.com/package/hypermaterial-vibrancy

**Comment by iamstarkov** [comment]
@danielheyman feel free [to add it to the list](https://github.com/bnb/awesome-hyper/blob/master/CONTRIBUTING.md#adding-to-this-list)
