### ISSUE TITLE
Is notification feature on list of being developed?

### ISSUE THREAD

**Issue by dankonino** [bnb/awesome-hyper#215]
hello guys, thanks for awesome hyper term. I just would like to see if someone is working on feature for making notifications after some task was finished in terminal. e.g:  `npm install` ? If no, I'd like to do it 🗡  ;)

**Comment by iamstarkov** [comment]
thats not hyper feature, you can do it in any terminal already

**Comment by iamstarkov** [comment]
let me get back in the office and i'll show you

**Comment by dankonino** [comment]
Yeah I would like to hook it up when the process is finished, because haven't seen that anywhere

**Comment by iamstarkov** [comment]
@dankonino here https://github.com/mikaelbr/node-notifier-cli
