### ISSUE TITLE
uninstall leaves behind context menu item

### ISSUE THREAD

**Issue by ksurl** [bnb/awesome-hyper#219]
edit: I just realized this repo is for plugins not the actual console. please delete this issue. I have previously tried to contact the dev but no response

![hypercontext](https://cloud.githubusercontent.com/assets/1371562/23493457/c794c680-fec0-11e6-9b70-0e4baac81258.png)
after uninstall, context menu in folder context still has a now blank icon with "hyper" as the text. searching hkroot\\*\shellex\contextmenuhandlers yields nothing. any idea on how to remove it? and update the uninstall script to remove it?

**Comment by iamstarkov** [comment]
@ksurl why did you close your issue?

**Comment by lholznagel** [comment]
>edit: I just realized this repo is for plugins not the actual console. please delete this issue. I have previously tried to contact the dev but no response

I think that's why. First sentence.

**Comment by iamstarkov** [comment]
didnt catch edit note in the start of the post

**Comment by darahak** [comment]
@ksurl It might not work for you, but I solved it by re-installing and uninstalling.

**Comment by ksurl** [comment]
@darahak I was able to delete it from a different registry path. got the fix from [here](https://github.com/zeit/hyper/issues/1242#issuecomment-267764993)
