### ISSUE TITLE
What about showing downloads per month ?

### ISSUE THREAD

**Issue by chabou** [bnb/awesome-hyper#223]
I've seen [plugin page](https://github.com/koajs/koa/wiki) for Koa.

What do you think about doing the same ? Downloads per month could indicate "usefulness level" of a plugin.
You can see the result [my fork](https://github.com/chabou/awesome-hyper/tree/add_downloads)

If you think this is a pertinent information, I could make a PR.

**Comment by iamstarkov** [comment]
can you elaborate more and explain more?

**Comment by chabou** [comment]
There a lot of plugin now and this is a long list.
For example, in my fork, you can see than `hyper-statusline` is a "blockbuster". If you are new to hyper, maybe you should have a look at it. the same for `hyper-tabs-enhanced`.
There is no quality or usefulness requirement to be on this list. Maybe DL/month could help to figure it out.

But maybe it is not a good idea, because with this, heavy downloaded packages would be heavier downloaded. And new plugin will not be so much downloaded with this information.

I think that feature is really useful for themes. Other plugins could explain their functionality and it is enough to be downloaded. It is more complicated for a theme. With DL/month, I can see than `hyper-snazzy`is a thing.

**Comment by Rawnly** [comment]
That's could be really cool!

**Comment by darahak** [comment]
Looks great!

Even the table is a nice improvement.
Suggestion: we might as well split names and descriptions for better readability.

**Comment by chabou** [comment]
split names and descriptions doesn't give a better readability because of hyphen word wrap.
You can see it [here](https://github.com/chabou/awesome-hyper/tree/add_downloads_3_cols)

**Comment by Vistur** [comment]
I think it's a nice improvement! Please PR and merge this!

**Comment by chabou** [comment]
PR done https://github.com/bnb/awesome-hyper/pull/230
