### ISSUE TITLE
Fun plugins

### ISSUE THREAD

**Issue by Valoutre** [bnb/awesome-hyper#231]
Hi,

I made two fun plugins that show up at start of the console :)

* [`hyper-doit`](https://github.com/Valoutre/hyper-doit) - DO IT ! 
* [`hyper-wheee`](https://github.com/Valoutre/hyper-wheee) - WHEEE ! 

Hope you'll enjoy it !

**Comment by delcore92** [comment]
Hi @Valoutre, thanks for your suggestions!

I would happily add your plugins to the list, but would prefer if you created two pull requests. 

Also, it's not entirely clear what your plugins do at a glance. Just as a general recommendation, you should add a screenshot or a gif to your `readme.md` so it's easier for people to visualise what they have to offer :) 

Going to close this issue out, looking forward to reviewing your prs :) 
Thanks!
