### ISSUE TITLE
No anchors on website

### ISSUE THREAD

**Issue by darahak** [bnb/awesome-hyper#232]
Hey @bnb :wave: 

Just noticed there is a website for the repo now, looking good.
The anchors for each section were lost though.

It looks like `compositor.json` has a pre-rendered version of the `README.md` file, but I'm not sure how we should proceed if we want to update it.
Is there a tool that we should use to generate the HTML? Does it mean there is a bug to be fixed on that tool?

**Comment by bnb** [comment]
@darahak Yes, it's a tool from compositor.io - I actually just trailed it with awesome-hyper, and didn't initially expect it to be up so fast 😅 That said, I went with it. I don't think there's group control yet, which is a bit of a PITA - that said, I'll reach out the compositor team to see what we can do. 👍
