### ISSUE TITLE
Unhandled Exception when trying to start Hyper terminal on Windows 10

### ISSUE THREAD

**Issue by postgrep** [bnb/awesome-hyper#243]
After running the Windows Installer Bootstrapper executable "hyper-Setup-1.3.1.exe", Hyper immediately trys to start it's main process. An unhandled exception is thrown immediately and the program exits.
Same happens when trying to start Hyper later on from the start menu.
Same happens when trying to uninstall the Package via Apps & Features

OS: Windows 10 Pro, 64 bit.
Version 1703 (OS Build 15063.138)

![jscript_error_in_main](https://cloud.githubusercontent.com/assets/1336461/25225272/1d854822-25c1-11e7-86d5-fb654687965a.PNG)

**Comment by darahak** [comment]
Try their repo instead: https://github.com/zeit/hyper
`awesome-hyper` is only about resources for Hyper, not Hyper itself.
