### ISSUE TITLE
hyper-material-solarized

### ISSUE THREAD

**Issue by ooJerryLeeoo** [bnb/awesome-hyper#244]
[hyper-material-solarized](https://github.com/ooJerryLeeoo/hyper-material-solarized) is a `light` and `dark` theme for **hyper**. It has material ui and better solarized dark/light color scheme.

**Comment by darahak** [comment]
👍 
Can you make a pull request?

**Comment by darahak** [comment]
Merged on https://github.com/bnb/awesome-hyper/pull/245
