### ISSUE TITLE
Change hyper-material-solarized to hyper-material-box

### ISSUE THREAD

**Issue by ooJerryLeeoo** [bnb/awesome-hyper#249]
Hi,

I'm maintainer of [hyper-material-solarized](https://github.com/ooJerryLeeoo/hyper-material-solarized), recently, I create a more hackable theme call [hyper-material-box](https://github.com/ooJerryLeeoo/hyper-material-box), and I decided to stop maintaining `hyper-material-solarized`, because `hyper-material-box` can do everything `hyper-material-solarized` can do, and even more.

So, what I asking here is to change the `hyper-material-solarized` to `hyper-material-box`

**Comment by chabou** [comment]
Please make a PR :)

**Comment by darahak** [comment]
Merged https://github.com/bnb/awesome-hyper/pull/250
