### ISSUE TITLE
Profiles or Projects

### ISSUE THREAD

**Issue by nam-co** [bnb/awesome-hyper#285]
Hi, thank you for this awesome list, I was wondering if Hyper has a profiles plugin like iTerm has, where you have access to a list of frequently used commands.

thanks

**Comment by delcore92** [comment]
Hi @nam-co, I'm not entirely sure that exists yet. There's lots of great features in iTerm that I would love to see make it to Hyper, you should create a plugin for it and add it to the list! 

Going to close this out for now, but if you need anymore help feel free to reach out to me on the [Zeit Community Slack](https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwj2jM707vjWAhUFjpQKHcDiDuAQFggmMAA&url=https%3A%2F%2Fzeit.chat%2F&usg=AOvVaw2zp8lFpz7EH3vvRk6qs6tX) 👍
