### ISSUE TITLE
Switch from bash/zsh to windows cmd?

### ISSUE THREAD

**Issue by ryantheleach** [bnb/awesome-hyper#293]
At the moment Hyper is configured to support bash/zsh by start up, but very occasionally I need to drop out to cmd line.

Is there a way to easily do this in hyper? I miss it when I have to use cmd or powershell.

**Comment by Empereol** [comment]
If you have `cmd` and/or `powershell` in your environment variables you should be able to call `cmd` or `powershell` to start those processes.

**Comment by ryantheleach** [comment]
Won't that end up in a crazy situation of potentially having them embedded all the way down?

e.g. bash->zsh (which already happens in order to get zsh to work) -> cmd -> bash -> zsh

that's like, 5 processes deep?

**Comment by Empereol** [comment]
Why would you enter bash/zsh from cmd? You could exit the cmd process to be back up to zsh.

**Comment by ryantheleach** [comment]
Ok, after some experimenting, with

`    shell: 'C:\\Windows\\System32\\bash.exe',` as the config

which autolaunches zsh, 

Attempting to exit zsh to bash works. attempting to exit bash to cmd results in a javascript error (But I wasn't totally expecting this to work, as the shell was set explicitly.)

once in zsh/bash, I am unable to work out how to get zsh to recognize cmd as something it can even run, (using the full path, havn't experiemented with adding C:\windows\System32\ to path as I think it's a bad idea.)

**Comment by bnb** [comment]
Hey there @ryantheleach - I just talked with @matheuss (one of the maintainers of Hyper, working at ZEIT), and he suggested you ask in the official Hyper repo to get more focused help: https://github.com/zeit/hyper

Do you think you can do that? Feel free to link back to this issue so you don't need to share all the context again.

**Comment by ryantheleach** [comment]
Thanks, I created an issue there and promptly closed it after I realized I forgot to search the existing issues.

https://github.com/zeit/hyper/issues/2450
