### ISSUE TITLE
Add my Hyper Plugin (Hyper-QuickSSH)

### ISSUE THREAD

**Issue by edhuardotierrez** [bnb/awesome-hyper#294]
Plugin to show a Quick List of your favorites SSH or others shell commands in Hyper:

https://www.npmjs.com/package/hyper-quickssh

**Comment by delcore92** [comment]
Hi @edhuardotierrez, 

Nice plugin, I would love to add it on the list.
Could you create a pull request as per our contribution guidelines: https://github.com/bnb/awesome-hyper/blob/master/CONTRIBUTING.md

**Comment by delcore92** [comment]
Feel free to @ me on your pull request. 
Will close this issue for now :)
