### ISSUE TITLE
[plugin] hyper-tray

### ISSUE THREAD

**Issue by tarutin** [bnb/awesome-hyper#296]
Hi,
plugin for minimalists — [tarutin/hyper-tray](https://github.com/tarutin/hyper-tray)

**Comment by darahak** [comment]
Looks like it's not published on npm yet?

**Comment by tarutin** [comment]
@darahak Done. https://www.npmjs.com/package/hyper-tray

**Comment by tarutin** [comment]
Hm, I found a little strange bug on Hyper: system tray closes itself after 1 minute on app started.

**Comment by danieldelcore** [comment]
Hi @tarutin, nice plugin!

It would be much appreciated if you could raise a pull request, as per our [contribution guidelines](https://github.com/bnb/awesome-hyper/blob/master/CONTRIBUTING.md). 

More than happy to review it for you 😊

**Comment by tarutin** [comment]
Hi @danieldelcore!
Unfortunately, system tray is still closes itself: zeit/hyper#2534
I think the problem is in Hyper updates module—exactly it's activate in a one minute.

**Comment by danieldelcore** [comment]
Oh i see, that sucks! 
Hopefully you can get to the bottom of it soon :)

**Comment by darahak** [comment]
@tarutin Closing the issue as it's been inactive for a while.
Feel free to open a PR if you solved your problem and want to add your plugin to the list.
