### ISSUE TITLE
'clear' command issue

### ISSUE THREAD

**Issue by ni7in** [bnb/awesome-hyper#299]
I configured git bash with hyper, everything works okay, except one thing when I try to clear my terminal, with the '**clear**' command It doesn't, and the cursor comes to the top of the lines and overlaps previous one. [Screenshot](https://i.gyazo.com/3dacb0f353ba061aed0aa9f5f580896e.png)

**Comment by subodhpareek18** [comment]
This is not the right repository for this issue. Please close this and file one here if it already doesn't exist.
https://github.com/zeit/hyper

**Comment by ni7in** [comment]
yeah right !!
