### ISSUE TITLE
[theme] hyper-oldschool

### ISSUE THREAD

**Issue by dimo89** [bnb/awesome-hyper#300]
https://github.com/dimo89/hyper-oldschool

**Comment by darahak** [comment]
Hi @dimo89, your theme looks great :+1: 
I highly recommend you open a PR to directly add it to the list.

You can find our contributing guidelines [here](https://github.com/bnb/awesome-hyper/blob/master/CONTRIBUTING.md), but it's pretty straightforward if you look at previous additions.

**Comment by dimo89** [comment]
Thanks, @darahak!
Opened PR: #301
