### ISSUE TITLE
Vim - :set mouse=a not working properly.

### ISSUE THREAD

**Issue by Etregoning** [bnb/awesome-hyper#317]
**OS version:** macOS High Sierra 10.13.3
**Vim version:** 8.0
**Hyper version:** 1.4.8
**Shell:** zsh 5.3

When using the `:set mouse=a` command in either the `.vimrc` or just straight into the vim command line, it allows scrolling with the mouse wheel, but it does not allow me to move the mouse cursor by clicking a location on the screen. When using this command in iTerm2, it works just fine. Do I need a plugin for this, or is it just not currently working properly?

Thanks.

**Comment by chabou** [comment]
With v1.4.8 stable release you have to use this plugin: https://www.npmjs.com/package/hyper-alt-click

In our upcoming v2, alt+click feature will be included.

Btw, please open issues in `hyper` repo: https://github.com/zeit/hyper : more people could answer.

**Comment by Etregoning** [comment]
Oh, oops! I didn't realize I was on the wrong repo, sorry! You answered my question though so I'll go ahead and close this! Thanks!
