### ISSUE TITLE
(Windows) script to select which shell you want on startup

### ISSUE THREAD

**Issue by legowerewolf** [bnb/awesome-hyper#319]
I've written it up [here](https://gist.github.com/legowerewolf/a3e0eb7830752488fec329c7bdcb2d2a), complete with install instructions.

Not sure where to put it, 'cause it's not a plugin or a theme or anything.

**Comment by chabou** [comment]
This is really awesome.

If you want, I can help you to make a plugin around this.

**Comment by legowerewolf** [comment]
That would be really cool. I don't really know much about NodeJS, so help would be appreciated.

**Comment by legowerewolf** [comment]
To be honest, I've never made a Node project. I've used some tools available via npm, but I've never made anything directly with Node.

**Comment by chabou** [comment]
If you want, I can make this plugin, and give you credits and write access on its GitHub repo. I could explain you all steps etc...

If you are ok, DM me on Zeit's slack

**Comment by legowerewolf** [comment]
Nah. This'll give me an excuse to learn Node. It's how I've learned other languages - pick a project and a language and learn as I go.
