### ISSUE TITLE
Hyperborder plugin completely blacks out emulator UI 

### ISSUE THREAD

**Issue by myDeveloperJourney** [bnb/awesome-hyper#327]
I have attempted to use the hyperborder plugin several times and have even managed to uninstall/reinstall hyper terminal more than once and have not had success.

**Comment by chabou** [comment]
Fixed in v1.0.1

**Comment by sgnl** [comment]
1.0.1 of hyper? or hyperborder

**Comment by myDeveloperJourney** [comment]
@sgnl Hey, yes, I was referring to the hyperborder plugin
