### ISSUE TITLE
Content coming over the header title after installing new themes

### ISSUE THREAD

**Issue by rahulaakash26** [bnb/awesome-hyper#331]
Installing hyper native theme makes the header to go at the back of contents. Not able to revert it even after installing some new theme.
![capture](https://user-images.githubusercontent.com/27017547/39614740-ba362468-4f8f-11e8-8c4d-87155634f0ef.JPG)

**Comment by iamstarkov** [comment]
consider to file this issue to actual hyper repo https://github.com/zeit/hyper
