### ISSUE TITLE
Add my color scheme :)

### ISSUE THREAD

**Issue by vemec** [bnb/awesome-hyper#43]
on git: https://github.com/vemec/hyperterm-vmc-dark
on npm: https://www.npmjs.com/package/hyperterm-vmc-dark

Thank you!

**Comment by matheuss** [comment]
Could you send a PR? With a better description, I think that is a good fit ☺️

**Comment by bnb** [comment]
@vemec Hey! Just wanted to follow up and say it would be awesome if you would be willing to send a PR for your color scheme! If you're not able to/would rather not, let us know and @matheuss or I will throw one up.

**Comment by vemec** [comment]
Sorry for the delay PR #118 👍
